# Generated by Django 5.0 on 2023-12-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='servings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
