# Generated by Django 5.0 on 2024-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
